# Generated by Django 4.2.3 on 2023-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("location", models.CharField(max_length=300, unique=True)),
                ("amb_number", models.CharField(max_length=13)),
                ("specialities", models.CharField(max_length=500)),
                ("logo", models.ImageField(upload_to="")),
            ],
        ),
    ]
